### ISSUE TITLE
Update vfile to 4.2.1

### ISSUE THREAD

**Issue by Monchi** [unifiedjs/unified#114]
### Subject of the feature

I'd like you to release a new version of unified with vfile 4.2.1

### Problem

vfile 4.2.1 includes [this PR](https://github.com/vfile/vfile/pull/59). With this change, users are able to use unified (and remark) in browser without `path` polyfill.

This change is a big improvement but the latest unified (9.2.0) still includes vfile 4.2.0.

Also, many repositories in unified ecosystem ignore `package-lock.json` and `yarn.lock` by `.gitignore`. Without them, the version of dependencies determined by the timing of `npm install`, so we cannot reproduce the behavior of a specific version. Maybe you should include them in the repository.

### Expected behavior

The new version of unified and remark with latest dependencies are released.

**Comment by wooorm** [comment]
You can `npm update` or remove your yarn lock and reinstall to get the update.

Adding package locks / yarn locks here has no effect on how you consume this project.
