### ISSUE TITLE
Logo not readable on github dark mode

### ISSUE THREAD

**Issue by lyderichti59** [unifiedjs/unified#120]
## Subject of the issue

The logo of Unified is not well displayed in the Readme of the repository when I use Github's dark-theme

## Your environment

Firefox, Github dark theme

## Steps to reproduce

Enable Github Dark Theme, and open the repository page.

## Expected behavior

The logo should be fully readable

![image](https://user-images.githubusercontent.com/34691216/106391284-d90ef580-63ec-11eb-84dc-e07eb9f93c65.png)

**Comment by wooorm** [comment]
thanks, fixed!
