### ISSUE TITLE
3rd overload signature of `FrozenProcessor.run` should accept `ParseTree` instead of `CompileTree`

### ISSUE THREAD

**Issue by alvinleung1996** [unifiedjs/unified#173]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unified 10.1.0

### Steps to reproduce

The 3rd overload signature of `FrozenProcessor.run` is incorrect.
https://github.com/unifiedjs/unified/blob/c3ba2cd7fce33c1133b95bc81d9b0a22dba5c409/index.d.ts#L307-L321

### Expected behavior

```typescript
run(
    node: Specific<Node, ParseTree>,
    file?: VFileCompatible | undefined
): Promise<Specific<Node, CompileTree>>
```

### Actual behavior

```typescript
run(
    node: Specific<Node, CompileTree>,
    file?: VFileCompatible | undefined
): Promise<Specific<Node, CompileTree>>
```

### Runtime

Node v16

### Package manager

Other (please specify in steps to reproduce)

### OS

Linux

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
Why? `ParseTree` is the input tree. `CompileTree` is the output tree.

**Comment by ChristianMurphy** [comment]
I'd second the why question.
@alvinleung1996 do you have an example where an input or output which should be supported, is not supported?

**Comment by alvinleung1996** [comment]
> Why? `ParseTree` is the input tree. `CompileTree` is the output tree.

For the first and second overload, `ParseTree` is the input tree and `CompileTree` is the output tree. But for the third one, `CompileTree` is the input tree and `CompileTree` is the output tree, which is inconsistent with the first two overloads and is incorrect.

https://github.com/unifiedjs/unified/blob/c3ba2cd7fce33c1133b95bc81d9b0a22dba5c409/index.d.ts#L273-L321

**Comment by wooorm** [comment]
Ah, I misunderstood. Thanks for clarifying!
I think you’re right. Care to create a pull request solving it?

**Comment by alvinleung1996** [comment]
> Ah, I misunderstood. Thanks for clarifying! I think you’re right. Care to create a pull request solving it?

OK, I will create a pull request for it.
