### ISSUE TITLE
this.use() doesn't respect plugin order when combined with unified().use()

### ISSUE THREAD

**Issue by siefkenj** [unifiedjs/unified#190]
Calling unified with

```
unified().use(function() {
    this.use(plugin1)
}).use(plugin2)
```

seems to execute the plugins in the order `pluign2` then `plugin1`. Is this the intended behavior? In my case, both plugins are transformer plugins.

**Comment by wooorm** [comment]
Yeah, this is intentional. First the plugins are added to a list, and not called yet. Only when they are needed, they are called, at which point your anonymous plugin adds `plugin1` also to the list.

**Comment by siefkenj** [comment]
I see. So what is the proper way for a plugin to push many transformers onto the stack?

**Comment by ChristianMurphy** [comment]
It sounds like you want to make a preset?
If so https://github.com/wooorm/remark-preset-wooorm gives an example of how that can look

**Comment by wooorm** [comment]
```js
function myPlugin()
  return function manyTransforms(tree, file) {
    transformOne(tree, file)
    transformTwo(tree, file)
  }
}
```

**Comment by siefkenj** [comment]
To use your example above, `transformOne` is the actual transform function and not the plugin, right? So to do with plugins, I would do
```javascript
function myPlugin(){
   return (tree, file) => {
      plugin1()(tree, file)
      plugin2()(tree, file)
   }
}
```
?

And if the transform returned a new tree instead of mutating the existing tree, I assume that would need to be manually accounted for?

**Comment by wooorm** [comment]
If you have multiple transforms, do what I did, not what you do.
If you have multiple plugins, use a preset as Christian points out, not what you do.

If transforms return things, you have to handle that.

This all seems like an XY problem. You are asking about a solution and not about your problem. Perhaps you can formulate your question in more words.
