### ISSUE TITLE
Notion Block AST

### ISSUE THREAD

**Issue by pixeleet** [unifiedjs/unified#223]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Not a problem, just wondering here if with the popularity of notion and how their blocks essentially map to markdown blocks it would be interesting to see a processor for MD->Notion / Notion->MD.

### Solution

Probably the Block AST of Notion needs to be implemented and mapped to Markdown. 

### Alternatives

There are some existing libraries to do this, some better some worse. 
Notion itself can export MD, its' just not available through their API as function. 
It might be just plain stupid of an idea. 
Idk. Let me know.

**Comment by ChristianMurphy** [comment]
Welcome @pixeleet! 👋 

> it would be interesting to see a processor for MD->Notion / Notion->MD.

It _could_ be.

Are you (@pixeleet) interested in helping to create/maintain these?
This would likely be a whole new organization/set of projects, similar to how `remark`, `rehype`, `redot`, and `mdx` exist on their own building off `unified`.

Or are you interested in sponsoring others to create these packages for you? (I know @wooorm, @Murderlon, and @remcohaszing at times do consultancy/sponsored work).

Speaking just for myself, I don't personally use Notion currently, nor have interest in spending personal time creating/maintaining a broad swath of packages I won't use in the foreseeable future.
But, I am happy to offer guidance and assistance to community members interested in spearheading new projects.

> Probably the Block AST of Notion needs to be implemented and mapped to Markdown.

There are some existing efforts to do mapping:
* https://github.com/Reinforz/Nishan
* https://github.com/Mongkii/notion-rehype
* https://github.com/dragonman225/nast

Some existing efforts to standardize the notion AST in:
* https://github.com/phuctm97/ntast
* https://github.com/dragonman225/nast/tree/master/packages/nast-types

And previous discussion on how that could/would fit with unified:
* https://github.com/orgs/unifiedjs/discussions/166

> Notion itself can export MD, its' just not available through their API as function.

Another alternative, would be gently nudging Notion to support markdown in their API. 🙂

**Comment by wooorm** [comment]
Closing as this is not a thing that is actionable to this repo.
I don’t have anything to add to Christian’s answer!

**Comment by pixeleet** [comment]
I'm happy to contribute on this, the outline seems clear to me, thanks for the elaborate response @ChristianMurphy
