### ISSUE TITLE
Error: No overload matches this call after library update.

### ISSUE THREAD

**Issue by olafurw** [unifiedjs/unified#227]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

11.0.1

### Steps to reproduce

We are using the library basically in the same way as the example

```
unified()
  .use(remarkParse)
  .use(remarkGfm)
  .use(remarkRehype)
// etc
```

And in version 10.1.2 it works great but if I update it to version 11.0.1 I get this error from `svelte-check (4.2.0)`

I tried clicking on these `Link to runnable example` to create a runnable example but none of the links work. Let me know if you still need it and I'll try to set something up.

```
No overload matches this call.
  Overload 1 of 3, '(preset?: Preset | null | undefined): Processor<undefined, undefined, undefined, undefined, undefined>', gave the following error.
    Type 'Plugin<[(Options | undefined)?], string, Root>' has no properties in common with type 'Preset'.
  Overload 2 of 3, '(list: PluggableList): Processor<undefined, undefined, undefined, undefined, undefined>', gave the following error.
    Argument of type 'Plugin<[(Options | undefined)?], string, Root>' is not assignable to parameter of type 'PluggableList'.
  Overload 3 of 3, '(plugin: Plugin<[], undefined, undefined>, ...parameters: [] | [boolean]): Processor<undefined, undefined, undefined, undefined, undefined>', gave the following error.
    Argument of type 'Plugin<[(Options | undefined)?], string, Root>' is not assignable to parameter of type 'Plugin<[], undefined, undefined>'.
      The 'this' types of each signature are incompatible.
        Type 'Processor<undefined, undefined, undefined, undefined, undefined>' is not assignable to type 'Processor<Root, Root, void, void>'.
          Types of property 'use' are incompatible.
            Type '{ <Parameters_2 extends unknown[] = [], Input extends string | Node | undefined = undefined, Output = Input>(preset?: Preset | null | undefined): Processor<undefined, undefined, undefined, undefined, undefined>; <Parameters_2 extends unknown[] = [], Input extends string | ... 1 more ... | undefined = undefined, Outp...' is not assignable to type '{ <PluginParameters extends any[] = any[], Input = Root, Output = Input>(plugin: Plugin<PluginParameters, Input, Output>, ...settings: [boolean] | PluginParameters): UsePlugin<...>; <PluginParameters extends any[] = any[], Input = Root, Output = Input>(tuple: [...] | [...]): UsePlugin<...>; (presetOrList: Preset | P...'.
              Types of parameters 'preset' and 'plugin' are incompatible.
                Type 'Plugin<any, any, any>' has no properties in common with type 'Preset'
```

### Expected behavior

No error

### Actual behavior

Error above.

### Affected runtime and version

vite@4.4.9

### Build and bundle tools

Vite

**Comment by remcohaszing** [comment]
The unified ecosystem is in the process of being upgraded with breaking changes. `unified` has been updated, but the remark plugins not yet. Use unified 10 until then.

**Comment by wooorm** [comment]
’cause it’s more detailed, and from a users’ perspective.

For my opinion, TS is a linter. It gets things wrong all the time. You don‘t always have to listen to it. You can use new tools already. And update the rest when that’s ready. It works, and if it doesn’t yet then raise an issue, so we can get stuff in earlier
