### ISSUE TITLE
remove `is-plain-obj` deps

### ISSUE THREAD

**Issue by Jayllyz** [unifiedjs/unified#248]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

https://e18e.dev/guide/cleanup.html
https://packages.ecosyste.ms/registries/npmjs.org/packages/is-plain-obj/dependent_packages?order=desc&sort=downloads
Unified is top 2 dependant of `is-plain-obj`

### Solution

Replace by a oneline function : 
```ts
function isPlainObject(v) {
	return v && typeof v === 'object' && (Object.getPrototypeOf(v) === null || Object.getPrototypeOf(v) === Object.prototype);
}
```

### Alternatives

.

**Comment by wooorm** [comment]
And then?

Do you use unified?

How far do you want to go? Do you want to inline every dependency?

---

Please at least put some time in your issue and respect our time too. There are of course alternatives and trade offs.

**Comment by wooorm** [comment]
How well does your code work? I’d assume it might break across realms, due to the `Object.prototype`?

**Comment by Jayllyz** [comment]
Hello, thanks for the fast answer.

To be honest, no I don't use unified. I'm just trying to help clean up the js ecosystem even if my contribution is a grain of salt.

"Inline every dependency" isn't what we're trying to do, but some packages shouldn't exist. Take a look at this PR where a contributor saves tons of data by removing `is-number` as ex.
https://github.com/micromatch/to-regex-range/pull/17

This oneline comes from : 

https://github.com/es-tooling/module-replacements/blob/main/manifests/micro-utilities.json

If you don't want to change it that's fine, don't worries.

**Comment by wooorm** [comment]
It’s used in case 1 because the dep is already there. The dep is there because of case 2.

**Comment by ChristianMurphy** [comment]
If there is a runtime performance reason, runtime correctness reason, or security reason to drop the dependency I'm all for it.

The premise of minifying code or documentation to save bandwidth downloading to a developer machine is not one I subscribe to.
Developers should have access to clear easy-to-understand code and documentation.
Code and documentation downloaded from a package manager is cached, it's a one time cost.

For folks who are concerned with the bandwidth, take it up with CI/CD providers and NPM itself to offer more tailored download options, rather than going after individual projects over a few kilobytes.

**Comment by Jayllyz** [comment]
Thanks for your feedback, I see that we have different opinions about such packages (even within e18e)

I don't want to get into a drama/debate because that's not the aim of this initiative. If you want to help or suggest things, I recommend you go to the discord.

Thank you, all the best for your projects and sorry for the time lost.
