### ISSUE TITLE
gettings console warnings from `node_modules/unified/index.d.ts`

### ISSUE THREAD

**Issue by dimaMachina** [unifiedjs/unified#250]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unified@11.05

### Steps to reproduce

gettings warnings from `index.d.ts`

### Expected behavior

clean terminal output

### Actual behavior

```sh
nextra:dev: "Value" is imported from external module "vfile" but never used in "node_modules/unified/index.d.ts".
nextra:dev: "CompileResults" is imported from external module "./lib/index.js" but never used in "node_modules/unified/index.d.ts".
```

### Affected runtime and version

node@20.16.0

**Comment by ChristianMurphy** [comment]
Welcome @dimaMachina! 👋 
That looks like a bug in Nextra not recognizing TypeScript doc comments, those values are used/needed for `{@linkcode Value}` and `{@linkcode CompileResults}` in that file.

**Comment by dimaMachina** [comment]
yes, they are used in JSDoc comments but does typescript understand `@linkcode`?

**Comment by ChristianMurphy** [comment]
Yes it does, and has for years https://github.com/microsoft/vscode/issues/57495

**Comment by dimaMachina** [comment]
Ty, sorry for noise
