### ISSUE TITLE
isarray warns on install

### ISSUE THREAD

**Issue by Arcanemagus** [unifiedjs/unified#30]
The `isarray` dependency throws a warning on install to just use `Array.isArray()` directly.

As I don't see an `engines` field in the `package.json` saying this needs to be compatible with an ancient version of Node.js that doesn't have that, it can probably just be removed.

**Comment by wooorm** [comment]
Yeah I saw that. Pff, it sucks.
I’m trying to keep my stuff working without polyfills though, caring about old browsers too.
So for now I’m keeping it in!
