### ISSUE TITLE
Accepting TypeScript definitions

### ISSUE THREAD

**Issue by pspeter3** [unifiedjs/unified#33]
Unified seems really cool! Would you be willing to accept TypeScript definition files?

**Comment by wooorm** [comment]
Thanks @pspeter3!

My view is (and solutions are) the same as Sindre om this! https://github.com/sindresorhus/ama/issues/439#issuecomment-280861804

👋

**Comment by hrajchert** [comment]
If somebody finds this issue, I'm working on some type definitions that I will eventually put on Definitely Type.

If you want to help me testing or contributing to the type definitions, all help is wanted :)

https://github.com/hrajchert/unified-typings-test

**Comment by ChristianMurphy** [comment]
As of https://github.com/unifiedjs/unified/pull/43 TS definitions are now included with `unified`.
