### ISSUE TITLE
Browser Support?

### ISSUE THREAD

**Issue by philippkuehn** [unifiedjs/unified#34]
Your basic markdown example isn't working in a browser.

```js
var unified = require('unified');
var markdown = require('remark-parse');
var remark2rehype = require('remark-rehype');
var doc = require('rehype-document');
var format = require('rehype-format');
var html = require('rehype-stringify');

unified()
  .use(markdown)
  .use(remark2rehype)
  .use(doc)
  .use(format)
  .use(html)
  .process('# Hello world!')
  .then(function (file) {
    console.log(String(file));
  }, function (err) {
    console.error(String(err));
  });
```

I will get an error

```js
ReferenceError: process is not defined
    at new VFile (VM11132 core.js:47)
    at VFile (VM11132 core.js:41)
    at executor (VM11126 index.js:369)
    at Function.process (VM11126 index.js:366)
```

The problem is this line in vfile
```js
this.cwd = process.cwd();
```
When commenting this line out everything is fine. Is this the expected behavior? I don't see anything in the docs that unified is only made for node.

**Comment by wooorm** [comment]
Yes, it should work, but it looks like the tool you use to build JavaScript (webpack? rollup? browserify) is  not configured to include native node modules. This really depends on the tool you’re using, so you’ll probably fare best by checking with them!

**Comment by cloverich** [comment]
@philippkuehn I'm sure you figured this out by now, but by default webpack adds and bundles Node dependencies when the target is web (the default, see webpack's [target documentation][1]). 

[1]: https://webpack.js.org/configuration/target/

**Comment by DrewHoo** [comment]
I'm hitting this issue, too while serving an Angular app (I'm on Angular 7). I'm using angular-cli to serve the app, which is using webpack, but which (maybe?) isn't supplying these node libraries. Would love to be able to use this, definitely think it could use some documentation for getting it to run in a browser.
