### ISSUE TITLE
plugin transformer does not support async functions

### ISSUE THREAD

**Issue by Pyrolistical** [unifiedjs/unified#35]
* node 8+
### Steps to reproduce
```js
function plugin() {
  return async function transformer(tree) {
    tree.children = await somethingAsync()
    return tree
  }
}
```
### Expected behaviour
Expect to be the same as
```js
function plugin() {
  return function transformer(tree) {
    return somethingAsync()
      .then((result) => {
        tree.children = result
        return tree
      })
  }
}
```
### Actual behaviour
The plugin is skipped.

### Root cause
https://github.com/serapath/x-is-function/issues/1

**Comment by wooorm** [comment]
Oh that sucks! Thanks for the write up. I’m fine with inlining the function with a fix here!
Or: maybe replace all `func(x)` checks with `typeof x === 'function'`, would the tests still pass when we do that?

**Comment by Pyrolistical** [comment]
ya, i don't know why `typeof x === 'function'` wasn't used in the first place

**Comment by wooorm** [comment]
Because regexes are [classified as functions in some browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#regular-expressions), but I think we can ignore that now.
