### ISSUE TITLE
Support React Native

### ISSUE THREAD

**Issue by craftzdog** [unifiedjs/unified#38]
### Subject of the issue

If you use `unified` on React Native app, you get following error while compilation:

```
error: bundling failed: Error: Unable to resolve module `path` from `/Users/.../node_modules/vfile/core.js`: Module `path` does not exist in the Haste module map
```

vfile requires `path` but there is no such module on RN app.

### Your environment

*   macOS (10.13.5)
*   unified@7.0.0
*   react-native@0.55.4

I just wanted to parse Markdown with `remark`.
A workaround is to install `path` npm module but I report it just in case if there is a better solution.

**Comment by craftzdog** [comment]
Also `process.cwd()` in vfile causes another error on run time:

```
Error in .on("change", function): TypeError: process.cwd is not a function
    at new VFile (core.js:40)
    at VFile (core.js:34)
    at Function.parse (index.js:269)
    at countNumberOfTasks (index.js:14)
    at migrateAddingNumOfTasks (migration.js:84)
    at Changes.<anonymous> (migrate.js:37)
    at Changes.EventEmitter.emit (events.js:81)
    at tryCatchInChangeListener (index-browser.js:44)
    at Object.Changes.opts.onChange (index-browser.js:82)
    at index.js:1372
```

**Comment by wooorm** [comment]
Is it possible to include `path` and `process` in react native, just like browserify (and webpack) do?

**Comment by craftzdog** [comment]
In React Native an app runs in JavaScriptCore which means that you don't have `path` and `process` basically. I guess React Native bundler doesn't do such thing like browserify. So I had to install [path](https://www.npmjs.com/package/path) and to create a shim like in order to get it to work:

```
process.cwd = function () {
    return '/';
}
```

**Comment by wooorm** [comment]
I think the solution could be [`node-libs-react-native`](https://github.com/parshap/node-libs-react-native). I’m sorry it’s hard...
The file stuff is essential for many tools built on unified, so I feel it should stay in vfile/unified though.

**Comment by craftzdog** [comment]
Okay. Thanks!

**Comment by craftzdog** [comment]
Before loading unified
