### ISSUE TITLE
Parser & Compiler can't be ES6 classes

### ISSUE THREAD

**Issue by mems** [unifiedjs/unified#48]
The following function doesn't detect ES6 classes as constructor functions:

https://github.com/unifiedjs/unified/blob/612d8dd0aa24aa9e150255f33ff7234a79958526/index.js#L403-L405

It should be more something like:

```js
const isConstructorFunction = (value) => Boolean(value && value.prototype && value.prototype.constructor);
```

**Comment by wooorm** [comment]
Hmm interesting. Wonder why classes don’t make methods enumerable.

Your code, however:

```js
const isConstructorFunction = (value) => Boolean(value && value.prototype && value.prototype.constructor);
```

Will accept any function. `isConstructorFunction(function () {}) // => true`

**Comment by mems** [comment]
Yes right, because `function(){}` could be used as constructor. But `() => {}` couldn't.

I think the only way to do handle that is to replace:

https://github.com/unifiedjs/unified/blob/612d8dd0aa24aa9e150255f33ff7234a79958526/index.js#L270-L274

with:

```js
let result = null;

if (newable(Parser)) {
  // "Parser" is a class or a function (but not a generator nor an arrow function)
  result = new Parser(String(file), file)
  
  if (result.hasOwnProperty("parse")) {
    result = result.parse()
  }
} else {
  result = Parser(String(file), file)
}
 
return result
```

Use a simple function a constructor isn't an issue :

```js
new function(){return ["test"]} // > Array [ "test" ]
```

**Comment by wooorm** [comment]
I think that works, and even simpler: the else statement isn't needed from what it seems. Could you try a PR for this?

**Comment by wooorm** [comment]
Unfortunately this will not work for `compiler`. Because when `compiler` is a normal function, it should return a string, and strings can’t be returned from a constructor.
