### ISSUE TITLE
Broken TypeScript definitions

### ISSUE THREAD

**Issue by JamesMessinger** [unifiedjs/unified#56]
### Subject of the issue

The TypeScript type definitions were refactored in PR #49, but the new definitions are invalid due to the use of `export default` instead of `export =`.  See [the TypeScript documentation](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require) to understand the difference between the two.

### Your environment

*   **OS**: Windows
*   **Packages**: 
    - unified v8.0.0
    - typescript: 3.5.2
*   **Env**: 
    - Node v12.2.0
    - NPM v6.9.0

### Steps to reproduce

You can see this bug in the wild in [the rehype-inline-svg plugin](https://github.com/JS-DevTools/rehype-inline-svg).  

1. __Clone the repo__<br>
`git clone https://github.com/JS-DevTools/rehype-inline-svg.git`

2. __Install dependencies__<br>
`npm install`

3. __Build the code__<br>
`npm run build` <br>
The build will succeed because the repo is currently using Unified v7.1.0 which has the old TypeScript definitions, which correctly used `export =` syntax.

4. __Upgrade Unified__
`npm install unified@8`

5. __Build the code again__<br>
`npm run build`<br>
This time the build will fail because of the new type definitions with incorrect `export default` syntax.

### Expected behaviour

**Option 1**
The TypeScript definitions should correctly reflect the fact that Unified exports a CommonJS module, _not_ an ESM module.

**Option 2**
Change Unified to export an ESM module instead of, or in addition to a CommonJS module. This way, the new TypeScript definitions will be correct.

### Actual behaviour

TypeScript builds fail because the type definitions are incorrect.

**Comment by ChristianMurphy** [comment]
Pull requests are welcome!
