### ISSUE TITLE
Readme on npm link to homepage not working

### ISSUE THREAD

**Issue by sw-yx** [unifiedjs/unified#68]
### Subject of the issue

npm README links to https://unified.js.org/ which is broken link

![image](https://user-images.githubusercontent.com/6764957/64881660-533caf80-d629-11e9-832f-ba73001e212c.png)

**Comment by ChristianMurphy** [comment]
The new url is https://unifiedjs.com, PRs are welcome!

**Comment by wooorm** [comment]
I think it's already fixed, just not published

**Comment by wooorm** [comment]
Released!
