### ISSUE TITLE
describe supported node versions on package.json

### ISSUE THREAD

**Issue by evilebottnawi** [unifiedjs/unified#70]
### Subject of the feature

Just add supported `node` range in `engines` into `package.json`

### Problem

Hard to undestand what is node supported, for example https://github.com/prettier/prettier/pull/6563 we can't update because we don't know supported versions

### Expected behaviour

Field present

### Alternatives

Maybe we can just add this information to documentation

Thanks

**Comment by ChristianMurphy** [comment]
officially supported node js can be found in package.json
https://github.com/unifiedjs/unified/blob/7086cef070f5ea311ef44b465895c546ba4527ab/.travis.yml#L5-L7

**Comment by evilebottnawi** [comment]
@ChristianMurphy sorry, but it is very unclear, `node` will be changed when LTS will be changed, but this doesn't mean current version is not supported latest LTS
/cc @wooorm

**Comment by ChristianMurphy** [comment]
@evilebottnawi unified 8 supports node 10 lts, node 12 lts, and node stable (currently also 12)

**Comment by wooorm** [comment]
'Node' indeed changes: we support the latest version of Node. The other value is the oldest we support. We also support the versions between, but in my experience testing more versions has resulted in false problems, and never caught actual problems.

The reason for not using engines is that we may support older versions, but having a strict engines field then shows incorrect warnings.

**Comment by evilebottnawi** [comment]
@wooorm will be great have docs about supported versions, because it is hard to update package in package like prettier, because we support old node versions

**Comment by wooorm** [comment]
Why is it hard for prettier? The linked issue is unrelated to the unified ecosystem

**Comment by evilebottnawi** [comment]
My mistake https://github.com/prettier/prettier/pull/6545, now we support node@6, but based on explain above it is not supported officially, but tests passed

**Comment by wooorm** [comment]
The way I understand it, Prettier already bundles unified, instead of having it as a dependency. That means that you can, on your side, compile with e.g., Babel, and never worry about what versions we support?

**Comment by evilebottnawi** [comment]
We already do this, but some developers install prettier from git directly and we still support them for currently major version (maybe we will change it in the future, it is our side). Here I just wanted to clarify the official node versions support, because I could not find it anywhere.

**Comment by wooorm** [comment]
Hmm. We don’t define this anywhere indeed. We do definitely support the ones in Travis (and between them), and try to support older versions. However, we also can’t develop everything here, and thus when a dependency decides to drop something (in a major), we update (also in a major).

We currently don’t have the bandwidth to maintain older versions of dependencies, or maintain several release lines.

**Comment by vweevers** [comment]
> The reason for not using engines is that we may support older versions, but having a strict engines field then shows incorrect warnings.

The problem with this is that the support policy itself is too vague ("we may support"). There's no way to codify that in `package.json` or elsewhere. I much prefer an explicit minimum version, even when it's higher than I wish, because at least I know what to expect.

**Comment by wooorm** [comment]
Some more points!

a) I’m not entirely sure what the best way to go here is
b) Code in unified projects is generally ES3, but we can’t control dependencies (if node packages update to use newer syntax, in a major, they typically don’t have a release line for previous semver majors, so we are forced to update)
c) Sometimes, dev-dependencies require newer Node versions that regular deps
d) We are currently close to everything that’s active, Carbon (sometimes Dubnium) and higher.
e) We don’t get many issues about this

**Comment by vweevers** [comment]
> I’m not entirely sure what the best way to go here is

IMO: explicitly declare the minimum version in `engines.node`. Whenever possible, delay dropping a node version, but once you do, be explicit and strict about it. There should be no gray area.

> Code in unified projects is generally ES3, but we can’t control dependencies (if node packages update to use newer syntax, in a major, they typically don’t have a release line for previous semver majors, so we are forced to update)

That's fine. When you're forced to upgrade node due to a dependency, update `engines.node` and release a major.

> Sometimes, dev-dependencies require newer Node versions that regular deps

Yeah, this can get in the way. I like how `standard` and `dependency-check` deal with this (to be kind to dependents): they're a noop on older node.

**Comment by wooorm** [comment]
> they're a noop on older node.

That’s smart! Wish more things did that!

> Whenever possible, delay dropping a node version, but once you do, be explicit and strict about it.

It sounds like we already do this the way you propose, except for the `engines` field.

I detailed why I don’t prefer engines [above](https://github.com/unifiedjs/unified/issues/70#issuecomment-536666466), but to add on it: `unified` has 100K+ dependent repos on GH, now add all the projects that are developed outside of GH, that’s a lot. There’s a big chance of it being somewhere in your dep tree, even if you don’t really run it. That means millions of `npm install`s by people who don’t know about unified, showing a warning.
If we’re talking about the couple of people (in comparison) building on top of unified, looking for what version of Node we support, then they’ll probably find this issue, the Travis config, or maybe a line in the docs; I feel like that’s a fine trade off? 🤷‍♂️

**Comment by vweevers** [comment]
Showing a warning would be a good thing! Because they're either 1) using the dependency on an unsupported node version. Or 2) they're not using it, so why is it in the dependency tree?

The majority of the packages that I (co)maintain, some with a similar situation as unified (like `prebuild-install` which ideally is just a silent tool hidden somewhere in the dependency tree), have an `engines.node` field. FWIW, I've never gotten a complaint about npm warnings. Only (in the past) about node version support being unclear.
