### ISSUE TITLE
Cannot use the same plugin multiple times in a processor

### ISSUE THREAD

**Issue by marko-knoebl** [unifiedjs/unified#79]
### Cannot use the same plugin multiple times in a processor

I have a use case where I want to apply the same plugin twice in a processor which doesn't seem to work

### Steps to reproduce

Here's a simple example that uses _rehype-format_ twice. Only the first use seems to succeed:

```js
const unified = require("unified");
const rehypeParse = require("rehype-parse");
const rehypeFormat = require("rehype-format");
const rehypeDocument = require("rehype-document");
const rehypeStringify = require("rehype-stringify");

const processor = unified()
  .use(rehypeParse, { fragment: true })
  .use(rehypeFormat)
  .use(rehypeDocument)
  .use(rehypeFormat)
  .use(rehypeStringify);

const input = "<div><h1>hello world</h1></div>";

const output = processor.processSync(input).toString();
console.log(output);
```

this produces the following output:

```html
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div>
  <h1>hello world</h1>
</div>

</body>
</html>
```

note that the original content was formatted, but the rest was not - the second pass of formatting did not occur

The same behavior occurs with other plugins

### Expected behavior

Allow plugins to be used multiple times

If that's not possible, it would be nice if attempting to use a plugin more than once threw an error

Alternatively, this should at least be documented with possible workarounds (I didn't find documentation on this)

**Comment by wooorm** [comment]
Hi there!

Thanks for the minimal reproduction! In this case, you could of course not use `rehype-format` twice, and only use the latter, for a fix. So, what I’m wondering is, was there something where you couldn’t do that, or was it just that it was unexpected?

The reason for not allowing plugins to be used twice, is to allow reconfiguring:

```js
.use(plugin, {alpha: true, bravo: true})
.use(plugin, {bravo: false, charlie: true})

function plugin(options) {
  console.log(options) // {alpha: true, bravo: false, charlie: true}
}
```

This is useful because [presets](https://github.com/unifiedjs/unified#preset) are often combined in a way where it doesn’t make sense to a) throw errors or b) to run multiple times with different configuration, and c) reconfiguring is the most intuitive.

**Comment by wooorm** [comment]
This could definitely be documented better in the readme here!

**Comment by marko-knoebl** [comment]
Thanks for your reply!

Now I see that `.use` actually does something entirely different when called multiple times with the same plugin. I think the documentation [here](https://github.com/unifiedjs/unified#processoruseplugin-options) could be expanded to describe the difference between the first and subsequent calls. If I have the time I may give this a go in the next days and create a pull request.

If it's of interest, I think there would be some use cases for using the same plugin multiple times:

### simple use case

One specific use case that I thought about in the past would be a logger:

```js
const processor = unified()
  .use(logger, {message: "starting processing"})
  .use(rehypeParse, { fragment: true })
  .use(logger, {message: tree => `parsed HTML consiting of ${tree.children.length} nodes`})
  .use(rehypeDocument)
  .use(logger, {message: "added document structure"})
  .use(rehypeFormat)
  .use(logger, {message: "formatted document"})
  .use(rehypeStringify);
```

I see now that this probably won't be possible.

### my actual use case

What actually caused me to stumble upon this behavior was [this script](https://github.com/marko-knoebl/courses-presentations/blob/build_imports/scripts/build_imports.js) that I'm working on at the moment: It uses two plugins that I wrote to build single-file HTML presentations. The plugins are called "rehype-inline" and "slides". In lines 26-32 the following happens:

1. _rehype-inline_ includes some external HTML fragments that are referenced via `<link rel="import">`
2. _slides_ does two things:
    - it transforms the HTML fragments that were just included (adding sections and classes)
    - it adds some references to stylesheets and scripts that are needed for the slides to work
3. _rehype-inline_ inlines the stylesheets and scripts that were just added

So in my use case I'm now using rehype-inline twice. I'm currently achieving this by doing this:

```js
const rehypeInline1 = () => rehypeInline();
const rehypeInline2 = () => rehypeInline();
```

Is there a better way?

**Comment by wooorm** [comment]
I’m definitely open to adding this as an example to the docs, appreciated!

---

Hmm, the way I see the collective, is that it’s good to have tiny utilities (hast/unist level) that do one thing, and one thing well, and they are composed into usable things as plugins (rehype ecosystem level).

Is there a way some of the inlining functionality could go into `slides`? Mostly, it’s useful for a plugin (e.g., `slides`) to be usable without first requiring another plugin (e.g., `inline`)

**Comment by marko-knoebl** [comment]
Thanks again for your reply! I'll write something up for the documentation and create a pull request.

As for the functionality of inlining and slides: The slides plugin doesn't require the inline plugin to be present before it. It's just that I'm creating quite big presentations of 100-200 slides where it makes sense to split the content into separate files and then assemble them from these separate files. But the slides plugin is also meant to work without any inlining being done before. But now I'll probably create a separate plugin (rehype-include) along with rehype-inline as the use cases are actually quite different.

**Comment by muescha** [comment]
in this case it overwrites the previous settings:
```javascript
  .use(require("retext-syntax-mentions"), { style: 'twitter'})
  .use(require("retext-syntax-mentions"), { style: 'github'})
```

this works:
```javascript
  .use(options => require("retext-syntax-mentions")(options), { style: 'twitter'})
  .use(options => require("retext-syntax-mentions")(options), { style: 'github'})
```

or shorter:
```javascript
  .use(() => require("retext-syntax-mentions")({ style: 'twitter'}))
  .use(() => require("retext-syntax-mentions")({ style: 'github'}))
```


is this an official workaround? maybe this can added to the docs?

**Comment by wooorm** [comment]
> is this an official workaround? maybe this can added to the docs?

There are reasons why plugins run once and that options are merged. I believe that’s the proper way to do it and I see performance problems and bugs with trying to work around it. So I don’t endorse a workaround. Maybe @ChristianMurphy has other opinions on this though.

**Comment by ChristianMurphy** [comment]
I'd second the recommendation to not duplicate plugins, as @wooorm mentions it can lead to difficult to triage bugs.
In general, I'd recommend fixing things at the plugin level, either contributing features to an existing plugin to make it more flexible, or creating a custom plugin if the needs are very specific.
