### ISSUE TITLE
examples of tools?

### ISSUE THREAD

**Issue by ianstormtaylor** [unifiedjs/unified#81]
Hello, I'm just wondering... I feel like a while ago I saw a tool that would highlight unnecessary words in a piece of text. And a few other examples of interesting prose-level tooling built on top of Unified. I could have sworn I found them via the Unified website, but cannot find them anymore.

Did these exist? Do they still exist?

(This is vague, I'm sorry!)

**Comment by ianstormtaylor** [comment]
Damn, of course as soon as I asked. They were these two:

- https://wooorm.com/readability/
- https://wooorm.com/write-music/

And they are in the "Showcase" section of the site. But I didn't realize from the homepage because it looked like that section was only for big existing OSS projects like Prettier and Gatsby.

**Comment by wooorm** [comment]
Hey Ian! Yup, those projects I made are still alive, glad you found them! (There’s also [common-words](https://wooorm.com/common-words/) and [short-words](https://wooorm.com/short-words/) btw)

I reworked the website last week, including many more examples to showcase, but indeed “hiding” those two compared to how big they were before.

I’m all ears if you have a suggestion on how to make it more clear that it’s not just big OSS things like prettier / gatsby!

**Comment by ianstormtaylor** [comment]
Very cool!

I'm honestly not sure. Although maybe the **Build** and **Learn** sections could also be expanded from 2 to 5 examples to match the others (maybe even specifically chosen for variety), and it might help give the idea that there are lots of possibilities.

Either way, awesome project!

**Comment by wooorm** [comment]
Agree, it’s much better, fixed!
