### ISSUE TITLE
tsc reports incorrect / missing types

### ISSUE THREAD

**Issue by NullVoxPopuli** [unifiedjs/unified#86]
### Subject of the issue

```
$ yarn tsc
node_modules/@types/vfile/index.d.ts:11:31 - error TS7016: Could not find a declaration file for module 'vfile-message'. '/{path to my project}/node_modules/vfile-message/index.js' implicitly has an 'any' type.
  Try `npm install @types/vfile-message` if it exists or add a new declaration (.d.ts) file containing `declare module 'vfile-message';`

11 import * as vfileMessage from 'vfile-message';
                                 ~~~~~~~~~~~~~~~

```

### Your environment

```
$ yarn why vfile-message
yarn why v1.22.0
[1/4] Why do we have the module "vfile-message"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "vfile-message@1.1.1"
info Reasons this module exists
   - "stylelint#postcss-markdown#remark#unified#vfile" depends on it
   - Hoisted from "stylelint#postcss-markdown#remark#unified#vfile#vfile-message"
info Disk size without dependencies: "20KB"
info Disk size with unique dependencies: "36KB"
info Disk size with transitive dependencies: "36KB"
info Number of shared dependencies: 1
=> Found "@types/vfile-message#vfile-message@2.0.2"
info This module exists because "stylelint#postcss-markdown#remark#unified#@types#vfile#@types#vfile-message" depends on it.
info Disk size without dependencies: "28KB"
info Disk size with unique dependencies: "60KB"
info Disk size with transitive dependencies: "60KB"
info Number of shared dependencies: 2
Done in 1.18s.
```

### Steps to reproduce

 - Be using TypeScript.
 - Check Types.

Tell us how to reproduce this issue.  Please provide a working and simplified example.

repo here: https://github.com/NullVoxPopuli/emberclear/pulls
```
cd packages/frontend
yarn tsc
```

### Expected behaviour

no type failures from vfile-message

**Comment by NullVoxPopuli** [comment]
cross reported here: https://github.com/vfile/vfile/issues/47

**Comment by ChristianMurphy** [comment]
vfile 4 and vfile-message 2 include typings built in.
vfile 3 and below as well as vfile-message 1 require typings to be installed from definitely typed.

either upgrade dependencies through the tree to get the versions that include typings or install `@types/vfile-message`

**Comment by ChristianMurphy** [comment]
FWIW, I use TS with Stylelint as well, and do not have have this issue.
There may be something specific to your build (webpack) or typescript configuration that is causing the conflict.
If you'd like help with that feel free to open a question at https://spectrum.chat/unified/type-definitions with more context on your build configuration.

**Comment by NullVoxPopuli** [comment]
I have: 
vfile 3.0.1, as a dep of unified.
unified 7.1.0 as a dep of remark.
remark 10.0.1 (latest is 11.0.2) as a dep of postcss-markdown # <-- this could be the issue here
postcss-markdown 0.36.0 (latest) as a dep of stylelint <- needs to upgrade remark
  - has remark specified as: `"remark": "^10.0.1",`
stylelint@13.2.0 (latest) is my direct dependency.

**Comment by NullVoxPopuli** [comment]
This looks promising: https://github.com/gucong3000/postcss-markdown/issues

:man_facepalming:

**Comment by NullVoxPopuli** [comment]
> FWIW, I use TS with Stylelint as well, and do not have have this issue.

you'd have to be using the master branch of postcss-markdown

**Comment by ChristianMurphy** [comment]
No customization

* `stylelint` 13.0.0
* `react-scripts` (Create react app) 3.3.0
* `typescript` 3.7.5

with tsconfig

```
{
  "compilerOptions": {
    "baseUrl": "src",
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": ["src"]
}
```

remark, unified, and vfile all are included with their standard transitive version included by stylelint.

**Comment by dangodev** [comment]
I’m seeing the same as @NullVoxPopuli. @ChristianMurphy just out of curiosity, if you delete `node_modules` and `package-lock.json`/`yarn.lock`, and `npm install`, does your build still work? I’m wondering if in your project you are locked to an older version resolution.

**Comment by ChristianMurphy** [comment]
@dangodev the `package-lock.json` and `node_modules` have been updated regularly, I did again today for good measure, the build still works.
I suspect it has to do with CRA setting `"skipLibCheck": true`

**Comment by dangodev** [comment]
> I suspect it has to do with CRA setting `"skipLibCheck": true`

Ah you may be onto something there

**Comment by NullVoxPopuli** [comment]
For those using the new(ish) `tsc --build`, `skipLibCheck` isn't an option (or at the very least isn't available via `--skipLibCheck`)

**Comment by ChristianMurphy** [comment]
@NullVoxPopuli this appears to be a tangentially related or unrelated to the original question.
To start a new discussion consider opening a thread at https://github.com/unifiedjs/unified/discussions

In addition, [the TypeScript docs](https://www.typescriptlang.org/docs/handbook/project-references.html#build-mode-for-typescript), make no mention of `build` restricting `skipLibCheck` it _may_ be unrelated to the mode.

**Comment by NullVoxPopuli** [comment]
:+1:

I just tested with the tsconfig.json flag, and it works as described by others.

(Wouldn't recommend it tho)

**Comment by ChristianMurphy** [comment]
@NullVoxPopuli nobody here said it was recommended. :raised_eyebrow: 
It's a work around for packages which haven't updated to the latest version which includes typings.

---

If you disagree with CRA's choice to use the flag, that would be something to take up with CRA directly https://github.com/facebook/create-react-app/issues
