### ISSUE TITLE
VFile types do not support property result

### ISSUE THREAD

**Issue by gurkerl83** [unifiedjs/unified#88]
The following commit distinguishes the return value of process and processSync as follows.

https://github.com/unifiedjs/unified/commit/c3ba172708e719baa963ee5826a7c81774a2784e

If the result a string, it is placed on the property contents, if not on result.

Currently the VFile Typescript Definition only defines contents. To achieve compatibility of the above described behavior the Typescript must be extended locally, this is of course not pretty.

I don't know how the communication to the VFile project is and if a change of this kind complies with the VFile specifications.

Thanks!

**Comment by wooorm** [comment]
We’re the same people, so communication is pretty good ;)

Would you be available to work on a PR to vfile, adding `.result`?

See also the discussion on vfile: https://github.com/vfile/vfile/issues/45

**Comment by wooorm** [comment]
Also: it’s [already okay to store anything directly on `file`](https://github.com/vfile/vfile#vfiledata), though that doesn’t seem to be in the types.

**Comment by ChristianMurphy** [comment]
> Also: it’s already okay to store anything directly on file, though that doesn’t seem to be in the types.

Even better, it already is in the types: https://github.com/vfile/vfile/blob/c395183cadb42b474b48f0484b5aab5f31584f31/types/index.d.ts#L23

**Comment by gurkerl83** [comment]
Hi I would love to do it, but there is an open discussion in the VFile project about what identifiers the variables should have in order to best understand them. I do not want to get in the way here. Maybe one of you can add it later.

**Comment by ChristianMurphy** [comment]
@gurkerl83 are you referring to https://github.com/vfile/vfile/issues/49?
That change likely won't start for a few months, it should be okay to update the typings without that change.

**Comment by creepinson** [comment]
Pretty sure there is 4.2.0 vfile  out now with correct types but it hasn't been updated in unified.

Any updates on this?

**Comment by ChristianMurphy** [comment]
vFile is a version range
https://github.com/unifiedjs/unified/blob/ad123690fede1e075dc27ff2eaf4cd82e30ea0f7/package.json#L59
it will automatically update to the latest minor.
If you're seeing an older version, please update your npm/yarn lock file.
